#! /usr/local/bin/node

var i = 0,
    j = 0,
    guitars = [],
    numOfGuitars = 0;

guitars = [
    "Fender",
    "Gibson",
    "Rickenbacker",
    "Ibanez"
]

numOfGuitars = 4;

for (i = 0; i < numOfGuitars; i++) {
    console.log('guitars ' + i + ': ' + guitars[i]);
}

for (j = 2; j < process.argv.length; j++) {
    console.log('arg ' + j + ': ' + process.argv[j]);
}
